name: Populate Project Fields

on:
  issues:
    types: [opened, edited]

jobs:
  populate-fields:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install js-yaml
        run: npm install js-yaml

      - name: Extract Data from fields
        run: |
          echo "${{ github.event.issue.body }}" > issue-body.yml
          node -e '
            const fs = require("fs");
            const yaml = require("js-yaml");
            const fields = fs.readFileSync("issue-body.yml", "utf8");
            const data = yaml.Load(fields);
            const loggedBy = data["Logged By"];
            console.log("Logged By:", loggedBy);
          ';
