name: Populate Project Fields

on:

  issues:

    types: [opened, edited]




jobs:

  populate-fields:

    runs-on: ubuntu-latest

    steps:
    - name: Available Data in body
      id: check_fields
      uses: actions/github-script@v4
      with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              console.log(context.payload)

    - name: Check if issue has custom fields
      id: fields
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const data = context.payload.issue.body;
          const regexPattern = /### (\w+)\n\n([\s\S]+?)(?:\n\n###|\n\n$)/g;
          let match;
          const fields = {};
          while ((match = regexPattern.exec(data)) !== null) {
            console.log(match[1]);
            const fieldName = match[1];
            const fieldValue = match[2].trim() || null; // Use null for empty field values
            fields[fieldName] = fieldValue; 
          }
          console.log(fields);
              console.log(fields);

            
            
    
