name: Populate Project Fields

on:
  issues:
    types: [opened, edited]

jobs:
  populate-fields:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Data from fields
        run: |
          echo "${{ github.event.issue.body }}" > issue-body.yml
          loggedBy=$(cat issue-body.yml | awk -F'\n' '/### Logged By/{print $2}')
          echo "Logged By: $loggedBy"
