name: Populate Project Fields

on:
  issues:
    types: [opened, edited]

jobs:
  populate-fields:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Data from fields
        run: |
          const yaml = require('yaml');
          cont yaml =  context.payload.issue.body;
          
          const data = yaml.parse(yamlScript);
          const loggedBy = data['Logged By'];
        
          console.log('Logged By:', loggedBy);
