name: Populate Project Fields

on:
  issues:
    types: [opened, edited]

jobs:
  populate-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Data from fields
        id: check_fields
        uses: actions/checkout@v2
        with:
          script: |
            const yaml = require('js-yaml');
            const fields = context.payload.issue.body;
            const data = yaml.safeLoad(fields);
            const loggedBy = data['Logged By'];
            console.log('Logged By:', loggedBy);
